# -*- coding: utf-8 -*-
"""Class_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5SqzjEDctxFTkDXGa3ufaDb289tyVhC

20240409 python 코딩
"""

print('test')
print('I am CJU')

print('colab python')